### ISSUE TITLE
 Frontend Developer OSF - Fortaleza

### ISSUE THREAD

**Issue by brenosoares** [frontend-ce/vagas#3]
## Requisitos

- Good experience with HTML/CSS/JavaScript;
- Must be able to generate from PSD;
- Must have experience with Angular 2+ development;
- Excellent oral & written communication skills in English.

## Local

 Fortaleza

## Contratação

CLT - Salário a combinar

## Como se candidatar

Por favor envie um email para breno.soares@ifactory.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front-end

## Labels

- Alocado
- CLT

**Comment by rivajunior** [comment]
@brenosoares a vaga continua aberta?

**Comment by brenosoares** [comment]
> 
> 
> @brenosoares a vaga continua aberta?

Continua @rivajunior
